language: python
before_install:
  - sudo bash -c "echo deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse >> /etc/apt/sources.list"
  - sudo apt-get update -qq
  - sudo apt-get install -y libleveldb1 libleveldb-dev
python:
  - "2.7"
env:
  - TOX_ENV=flake8
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py27-bench
  - TOX_ENV=py33-bench
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
notifications:
  email:
    - on_success: change
  irc:
      channels:
        - "chat.freenode.net#onitu"
      use_notice: true
      skip_join: true
