language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
# command to run tests
script:
  - py.test tests -v
  - flake8 onitu tests
notifications:
  email:
    - onitu_2015@labeip.epitech.eu
    - on_success: change
  irc:
      channels:
        - "chat.freenode.net#onitu"
      use_notice: true
      skip_join: true
