language: python
python:
  - "2.7"
env:
  - TOX_ENV=flake8
  - TOX_ENV=py27
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
notifications:
  email:
    - onitu_2015@labeip.epitech.eu
    - on_success: change
  irc:
      channels:
        - "chat.freenode.net#onitu"
      use_notice: true
      skip_join: true
