version: '{build}'

environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"

install:
  - "git clone https://github.com/bureau14/leveldb.git"
  - "cd leveldb/ && cmake"

build: off
deploy: off

test_script:
  - "%PYTHON%/Scripts/py.test.exe -v tests/"
