version: '{build}'

environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"

install:
  - "msbuild.exe"

build: off
deploy: off

test_script:
  - "%PYTHON%/Scripts/py.test.exe -v tests/"
